ei60doors/custom_catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from ei60doors.custom_catalog.views import FilterProductView, popular_items_pagination

urlpatterns = [
    url(r'^filter_products/$', FilterProductView.as_view(), name='filter_products'),
    url(r'^novelties_list/$', popular_items_pagination, name='novelties_list'),
]

ei60doors/custom_pages/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from ei60doors.custom_pages.views import pages_list_pagination

urlpatterns = [
    url(r'^pages_list/(?P<obj_id>\d+)/$', pages_list_pagination, name='pages_list'),
]

ei60doors/service/urls.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView
from django.conf.urls import url
from django.conf import settings

from .views import handler404, handler500, sitemap


urlpatterns = [
    url(r'^sitemap.xml$', sitemap, name='sitemap'),
    url(r'^search/', TemplateView.as_view(template_name='service/search.html'), name='search'),
]

if settings.DEBUG:
    urlpatterns = [
        url(r'^404/$', handler404, name='handler404'),
        url(r'^500/$', handler500, name='handler500'),
    ] + urlpatterns

ei60doors/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from pages import views as pages_views
from filebrowser.sites import site
from ei60doors.custom_catalog.xml import yml_export, xml_export, yml_direct


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('attachment.urls')),
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^products.yml$', yml_export),
    url(r'^direct-products.yml$', yml_direct),
    url(r'^google-products.xml$', xml_export),
    url(r'^custom_feedback/', include('ei60doors.custom_feedback.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^custom_catalog/', include('ei60doors.custom_catalog.urls')),
    url(r'^custom_pages/', include('ei60doors.custom_pages.urls')),
    url(r'^', include('ei60doors.service.urls')),
    url(r'^(?P<path>.*)/$', pages_views.details, name='pages-details-by-path'),
    url(r'^$', pages_views.details, name='pages-root', kwargs={'path': u''})
]

if settings.DEBUG:
    urlpatterns = [
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler404 = 'ei60doors.service.views.handler404'
handler500 = 'ei60doors.service.views.handler500'

try:
    from ei60doors.service.models import SiteSettings
    site_settings = SiteSettings.objects.all().first()
    if site_settings:
        admin.site.site_header = site_settings.name
except:
    pass

ei60doors/custom_catalog/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.shortcuts import reverse
from tinymce.models import HTMLField
from catalog.models import CatalogBase
from catalog.utils import get_content_objects, get_sorted_content_objects
from pages.models import Page
from django.core.cache import cache
from django.db.models import Max, Min


CONSTRUCTION_CHOICES = (
    (0, 'Однопольная'),
    (1, 'Полуторапольная'),
    (2, 'Двупольная'),
)

FIREPROOF_CHOICES = (
    (0, 'Ei-30'),
    (1, 'Ei-60'),
    (2, 'Ei-90'),
)

GROUP_CHOICES = (
    (1, 'Двери по назначению'),
    (2, 'Двери по наружной отделке'),
    (3, 'Двери по особенностям')
)

SORT_CHOICES = (
    ('asc', "Сначала дешевые"),
    ('desc', "Сначала дорогие"),
    ('new', "Новинки сверху"),
)


class CatalogMixin:

    def get_products_count(self):
        result = cache.get(self.cache_key()+'_products_count', None)
        if not result:
            result = self.get_products().count()
            cache.set(self.cache_key()+'_products_count', result, 600000)
        return result

    def cache_key(self):
        return '%s_%d' % (self.__class__.__name__, self.id)

    def get_min_price(self):

        result = cache.get(self.cache_key()+'_min_price', 0)
        if not result:
            prices = self.get_products().aggregate(Min('price'))
            result = prices['price__min']
            cache.set(self.cache_key()+'_min_price', result, 600000)
        return result

    def get_max_price(self):
        result = cache.get(self.cache_key()+'_max_price', 0)
        if not result:
            prices = self.get_products().aggregate(Max('price'))
            result = prices['price__max']
            cache.set(self.cache_key()+'_max_price', result, 600000)
        return result


class Root(CatalogBase, CatalogMixin):
    class Meta:
        verbose_name = u'корневая страница'
        verbose_name_plural = verbose_name

    slug = ''
    title = models.CharField(
        verbose_name=u'название',
        max_length=400
    )
    long_title = models.CharField(
        verbose_name=u'длинное название',
        max_length=400,
        blank=True, null=True
    )
    sort = models.CharField(
        verbose_name=u'Сортировать товары',
        default='new',
        choices=SORT_CHOICES,
        max_length=255
    )

    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self, *args, **kwargs):
        return u'Корневая страница'

    def get_absolute_url(self):
        return reverse('catalog-root')

    def get_products(self):
        result = cache.get(self.cache_key() + '_products')
        if result is None:
            result = Product.objects.filter(show=True).order_by('-id')
            if self.sort == 'asc':
                result = result.order_by('price')
            elif self.sort == 'desc':
                result = result.order_by('-price')
            else:
                result = result.order_by('-id')
            cache.set(self.cache_key() + '_products', result, 600000)
        return result


class Product(CatalogBase):

    class Meta:
        verbose_name = u'товар'
        verbose_name_plural = u'товары'

    leaf = True
    title = models.CharField(
        verbose_name=u'название',
        max_length=400
    )
    long_title = models.CharField(
        verbose_name=u'длинное название',
        max_length=400,
        null=True,
        blank=True
    )
    google_prefix = models.CharField(
        verbose_name=u'Префикс Google Merchant',
        max_length=400,
        blank=True, null=True,
        help_text=u'Добавляет префикс к длинному названию товара в google merchant'
    )
    exclude_google_merchant = models.BooleanField(
        verbose_name=u'Не выгружать в Google Merchant',
        default=False
    )
    exclude_direct_yml = models.BooleanField(
        verbose_name=u'Не выгружать в Yandex Директ',
        default=False,
    )
    price = models.PositiveIntegerField(
        verbose_name=u'цена',
        default=0
    )
    old_price = models.PositiveIntegerField(
        verbose_name=u'старая цена',
        default=0
    )
    habarytes = models.TextField(
        verbose_name=u'Габариты',
        max_length=255,
        blank=True,
        null=True
    )
    construction = models.IntegerField(
        verbose_name=u'Конструкция',
        choices=CONSTRUCTION_CHOICES,
        blank=True,
        null=True
    )
    fireproof = models.IntegerField(
        verbose_name=u'Огнестойкость',
        choices=FIREPROOF_CHOICES,
        blank=True,
        null=True
    )
    readiness = models.CharField(
        verbose_name=u'Готовность',
        max_length=255,
        blank=True,
        null=True
    )
    delivery = models.CharField(
        verbose_name=u'Доставка',
        max_length=255,
        blank=True,
        null=True,
    )
    mounting = models.CharField(
        verbose_name=u'монтаж',
        max_length=500,
        blank=True,
        null=True
    )
    specs = HTMLField(
        verbose_name=u'Характеристики',
        blank=True,
        null=True
    )
    finish = models.ManyToManyField(
        Page,
        verbose_name=u'Варианты отделки',
        related_name='finish_products',
        limit_choices_to={
            'template': 'pages/finish.html',
            'status': Page.PUBLISHED,
        },
        blank=True
    )
    services = HTMLField(
        verbose_name=u'Услуги',
        blank=True,
        null=True
    )
    gallery = models.ForeignKey(
        Page,
        verbose_name=u'Галерея',
        related_name='gallery_products',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        limit_choices_to={
            'template': 'pages/gallery.html',
            'status': Page.PUBLISHED,
        }
    )

    def __str__(self):
        return '%s - %s' % (self.title, self.id)


class Section(CatalogBase, CatalogMixin):
    class Meta:
        verbose_name = u'раздел'
        verbose_name_plural = u'разделы'

    title = models.CharField(
        verbose_name=u'название',
        max_length=400
    )
    long_title = models.CharField(
        verbose_name=u'длинное название',
        max_length=400,
        null=True,
        blank=True
    )
    google_prefix = models.CharField(
        verbose_name=u'Префикс Google Merchant',
        max_length=400,
        blank=True, null=True,
        help_text=u'Добавляет префикс к длинному названию дочерних товаров в google merchant'
    )
    google_merchant = models.BooleanField(
        verbose_name=u'Выгружать в Google Merchant',
        default=True,
        help_text=u'Наследуется в товары'
    )
    sort = models.CharField(
        verbose_name=u'Сортировать товары',
        default='new',
        choices=SORT_CHOICES,
        max_length=255
    )
    group = models.IntegerField(
        verbose_name=u'Группа',
        choices=GROUP_CHOICES,
        blank=True,
        null=True
    )
    habarytes = models.TextField(
        verbose_name=u'Габариты',
        max_length=255,
        blank=True,
        null=True
    )
    construction = models.IntegerField(
        verbose_name=u'Конструкция',
        choices=CONSTRUCTION_CHOICES,
        blank=True,
        null=True
    )
    fireproof = models.IntegerField(
        verbose_name=u'Огнестойкость',
        choices=FIREPROOF_CHOICES,
        blank=True,
        null=True
    )
    readiness = models.CharField(
        verbose_name=u'Готовность',
        max_length=255,
        blank=True,
        null=True
    )
    delivery = models.CharField(
        verbose_name=u'Доставка',
        max_length=255,
        blank=True,
        null=True,
    )
    mounting = models.CharField(
        verbose_name=u'монтаж',
        max_length=500,
        blank=True,
        null=True
    )
    specs = HTMLField(
        verbose_name=u'Характеристики',
        blank=True,
        null=True
    )
    finish = models.ManyToManyField(
        Page,
        verbose_name=u'Варианты отделки',
        related_name='finish_sections',
        limit_choices_to={
            'template': 'pages/finish.html',
            'status': Page.PUBLISHED,
        },
        blank=True
    )
    services = HTMLField(
        verbose_name=u'Услуги',
        blank=True,
        null=True
    )
    gallery = models.ForeignKey(
        Page,
        verbose_name=u'Галерея',
        related_name='gallery_sections',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        limit_choices_to={
            'template': 'pages/gallery.html',
            'status': Page.PUBLISHED,
        }
    )

    def __str__(self):
        return self.title

    def get_products(self):
        result = cache.get(self.cache_key() + '_products')
        if result is None:
            result = Product.objects.filter(tree__parent__object_id=self.id, show=True)
            if self.sort == 'asc':
                result = result.order_by('price')
            elif self.sort == 'desc':
                result = result.order_by('-price')
            else:
                result = result.order_by('-id')
            cache.set(self.cache_key() + '_products', result, 600000)
        return result


class Category(CatalogBase, CatalogMixin):
    class Meta:
        verbose_name = u'категория'
        verbose_name_plural = u'категории'

    leaf = True

    title = models.CharField(
        verbose_name=u'название',
        max_length=400
    )
    long_title = models.CharField(
        verbose_name=u'длинное название',
        max_length=400
    )
    sort = models.CharField(
        verbose_name=u'Сортировать товары',
        default='new',
        choices=SORT_CHOICES,
        max_length=255
    )
    group = models.IntegerField(
        verbose_name=u'Группа',
        choices=GROUP_CHOICES,
        blank=True,
        null=True
    )
    products = models.ManyToManyField(
        Product,
        verbose_name=u'Товары',
        blank=True
    )

    def __str__(self):
        return self.title

ei60doors/custom_catalog/views.py
from django.views.generic import TemplateView
from ei60doors.custom_catalog.models import Section, Category, Root, Product
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.template import loader
from django.shortcuts import render


class FilterProductView(TemplateView):
    """ Фильтр каталога """

    template_name = 'catalog/parts/product_list.html'

    def get(self, request):
        ct_id = request.GET.get('ct')
        obj_id = request.GET.get('obj')
        dir = request.GET.get('dir')
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')
        if ct_id and obj_id:
            object = ContentType.objects.filter(id=ct_id).first().get_all_objects_for_this_type().filter(id=obj_id).first()
        else:
            object = Root.objects.first()

        products = object.get_products()
        if dir == 'asc':
            products = products.order_by('price')
        elif dir == 'desc':
            products = products.order_by('-price')

        if min_price:
            products = products.filter(price__gte=min_price)
        if max_price:
            products = products.filter(price__lte=max_price)

        context ={
            'product_list': products,
        }
        if request.is_ajax():
            html = loader.render_to_string(self.template_name, context, request)
            response_data = {
                'html': html,
                'products_count': products.count(),
            }
            return JsonResponse(response_data)
        return self.render_to_response(context)


def popular_items_pagination(request):

    novelties = Product.objects.filter(show=True,).order_by('-id')

    html = loader.render_to_string(
        'catalog/parts/novelties_list.html',
        {'novelties': novelties},
        request
    )
    response_data = {
        'html': html
    }

    return JsonResponse(response_data)

ei60doors/custom_feedback/views.py
from django.shortcuts import render
from feedback.utils import get_feedback_form
from feedback.settings import PREFIX_KEY_FIELDS


def ajax_reset_form(request):
    form_key = request.GET.get('form_key')
    form = get_feedback_form(form_key)
    if PREFIX_KEY_FIELDS:
        form.prefix = form_key
    templates = ['feedback/%s/feedback.html' % form_key, 'feedback/feedback.html']
    return render(request, templates, {'form': form})

ei60doors/custom_pages/views.py
from pages.models import Page
from django.http import JsonResponse
from django.template import loader
from django.http import HttpResponseNotFound


def pages_list_pagination(request, obj_id):

    page = Page.objects.filter(id=obj_id).first()
    if page:
        children = page.get_children_for_frontend()

        html = loader.render_to_string(
            'pages/parts/card_list.html',
            {'children': children, 'current_page': page},
            request
        )
        response_data = {
            'html': html
        }

        return JsonResponse(response_data)
    return HttpResponseNotFound

ei60doors/service/views.py
# -*- coding: utf-8 -*-
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.shortcuts import render
from pages.models import Page
from .models import ErrorPage
from ei60doors.custom_catalog.models import Root, Section, Category, Product


def handler404(request, exception=None):
    obj, _ = ErrorPage.objects.get_or_create(type='404')
    obj.generate_static_page(request)
    return render(request, 'service/404.html', {'object': obj}, status=404)


def handler500(request):
    obj, _ = ErrorPage.objects.get_or_create(type='500')
    obj.generate_static_page(request)
    return render(request, 'service/500.html', {'object': obj}, status=500)


def sitemap(request):
    sitemaps = {
        'pages': GenericSitemap({
            'queryset': Page.objects.filter(status=Page.PUBLISHED),
            'date_field': 'last_modification_date',
        }),
        'root': GenericSitemap({
            'queryset': Root.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'section': GenericSitemap({
            'queryset': Section.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'category': GenericSitemap({
            'queryset': Category.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'product': GenericSitemap({
            'queryset': Product.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
    }
    return sitemap_view(request, sitemaps, template_name='service/sitemap.xml')

ei60doors/templates/catalog/parts/filter_form.html
<form class="filter__form filter-form" action="{% url 'filter_products' %}" novalidate>
    <input type="hidden" name="ct" value="{{ object.tree.get.content_type.id }}">
    <input type="hidden" name="obj" value="{{ object.id }}">

    <div class="filter">
        <div class="filter__left">
            <div class="filter__select select" cursor-class="link-hover">
                <select name="dir" id="id_dir">
                    <option value="asc" {% if object.sort == 'asc' %}selected{% endif %}>Сначала дешевые</option>
                    <option value="desc" {% if object.sort == 'desc' %}selected{% endif %}>Сначала дорогие</option>
                    <option value="new" {% if object.sort == 'new' or not object.sort %}selected{% endif %}>Сначала новинки</option>
                </select>
            </div>

            <div class="filter__count products_count">
                Всего: <span>{{ product_list.count }}</span>
            </div>
        </div>

        <div class="filter__right">
            <button class="filter__btn filter__btn--hidden-lg filter__btn--mobile filter-open" cursor-class="link-hover" type="button">
                По цене
            </button>
            <div class="filter__option">
                <button class="filter__option-close filter-close" cursor-class="link-hover" type="button">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M15.9208 1.77817L9.55679 8.14214L15.9208 14.5061L14.5065 15.9203L8.14258 9.55635L1.77862 15.9203L0.364404 14.5061L6.72836 8.14214L0.364404 1.77817L1.77862 0.363961L8.14258 6.72792L14.5065 0.363961L15.9208 1.77817Z" fill="black"/>
                    </svg>
                </button>
                <div class="filter__option-title">
                    Цена, руб:
                </div>
                <div class="filter__option-list">
                    <input class="filter__option-input filter__option-input--min" id="min_price" name="min_price" type="number" placeholder="от {{ object.get_min_price|default:0 }}" step="500" min="{{ object.get_min_price|default:0 }}" max="{{ object.get_max_price|default:0 }}" value="{{ object.get_min_price|default:0 }}">
                    <input class="filter__option-input filter__option-input--max" id="max_price" name="max_price" type="number" step="500" placeholder="до {{ object.get_max_price|default:0 }}" min="{{ object.get_min_price|default:0 }}" max="{{ object.get_max_price|default:0 }}" value="{{ object.get_max_price|default:0 }}">
                </div>
                <button class="filter__btn filter__option-btn" cursor-class="link-hover" type="submit">
                    Найти
                </button>
            </div>
        </div>
    </div>
</form>

ei60doors/templates/catalog/parts/finish_list.html
{% load attachment_tags %}
<div class="facing">
    <div class="facing__list">
        {% for finish in finish_list %}
            {% get_images for finish as images %}
            {% if images %}
                <div class="facing__item">
                    <div class="facing__title">
                        {{ finish.title }}
                    </div>
                    <div class="facing__slider mfp-gallery" cursor-class="slider-hover">
                        <div class="facing--slider swiper-container">
                            <div class="swiper-wrapper">
                                {% for image in images %}
                                    <div class="facing__slide swiper-slide">
                                        <a class="facing-mincard" href="{{ image.watermarkpicture.url }}">
                                            <div class="facing-mincard__img">
                                                <img src="{{ image.facingmin.url }}" alt="{{ image.title|default:finish.title }}" title="{{ image.title|default:finish.title }}">
                                            </div>
                                            {% if image.title %}
                                                <span class="facing-mincard__title">
                                                    {{ image.title }}
                                                </span>
                                            {% endif %}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-scrollbar slider__scrollbar"></div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

ei60doors/templates/catalog/parts/novelties_list.html
{% load pagination_tags feedback_tags %}
{% if novelties %}
    {% autopaginate novelties 12 %}

    {% for product in novelties %}
        <div class="catalog__grid-3 catalog__grid-4--md catalog__grid-6--xs">
            {% include 'catalog/parts/product_card.html' %}
        </div>
    {% endfor %}

    <div class="catalog__grid-12 loader__show-more show-more-novelties">
        <div class="loader__content loader-js">
            <div class="loader"></div>
        </div>
        {% paginate using 'pagination/show_more_novelties.html' %}
        <a class="btn btn--red" cursor-class="link-hover" href="{% url 'catalog-root' %}">
            В каталог
        </a>
    </div>
{% endif %}

ei60doors/templates/catalog/parts/product_card.html
{% load attachment_tags base_tags custom_catalog_tags %}
<a class="product-card" cursor-class="link-hover" href="{{ product.get_absolute_url }}">
    {% get_images for product as images %}
    {% if images %}
        <div class="product-card__preview">
            <img src="{{ images.0.productcard.url }}" alt="{{ image.title|default:product.title }}" title="{{ image.title|default:product.title }}">
        </div>
    {% endif %}

    <div class="product-card__content">
        <div class="product-card__title">
            {{ product.title }}
        </div>
        <ul class="product-card__info">
            <li>
                <span>Арт:</span> {{ product.id }}
            </li>
            {% get_inherited_field product 'get_fireproof_display' display=True as fireproof %}
            {% if fireproof %}
                <li>
                    <span>Огнестойкость:</span> {{ fireproof }}
                </li>
            {% endif %}
        </ul>
        <div class="product-card__bottom {% if product.old_price %}product-card__bottom--margin{% endif %}">
            {% if product.price %}
                <div class="product-card__price">
                    <span>{{ product.price|price_format }}</span> руб.
                </div>
                {% if product.old_price %}
                    <div class="product-card__oldprice">
                        {{ product.old_price|price_format }} руб.
                    </div>
                {% endif %}
            {% else %}
                <div class="product-card__price">
                    <span>
                        Цена по запросу
                    </span>
                </div>
            {% endif %}
        </div>
    </div>
</a>

ei60doors/templates/catalog/parts/product_list_slider.html
{% if products %}
    <div class="goods">
        <div class="goods__slider">
            <div class="slider goods--slider swiper-container" cursor-class="slider-hover">
                <div class="swiper-wrapper">
                    {% for product in products %}
                        <div class="goods__item swiper-slide">
                            {% include 'catalog/parts/product_card.html' %}
                        </div>
                    {% endfor %}
                </div>
                <div class="slider__pagination swiper-pagination"></div>
            </div>
        </div>
    </div>
{% endif %}

ei60doors/templates/catalog/parts/sections_list.html
{% load custom_catalog_tags %}
{% get_sorted_categories_and_sections as sections %}
{% if sections %}
    <div class="tags tags--default scroll-custom-x-shadow">
        <div class="tags__slider tags--slider swiper-container">
            <div class="swiper-wrapper">
                {% for section in sections %}
                    <div class="tags__item swiper-slide">
                        <a class="tags__link" cursor-class="link-hover" href="{{ section.get_absolute_url }}">
                            #{{ section.title }}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}