ei60doors/custom_catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from ei60doors.custom_catalog.views import FilterProductView, popular_items_pagination

urlpatterns = [
    url(r'^filter_products/$', FilterProductView.as_view(), name='filter_products'),
    url(r'^novelties_list/$', popular_items_pagination, name='novelties_list'),
]

ei60doors/custom_pages/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from ei60doors.custom_pages.views import pages_list_pagination

urlpatterns = [
    url(r'^pages_list/(?P<obj_id>\d+)/$', pages_list_pagination, name='pages_list'),
]

ei60doors/service/urls.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView
from django.conf.urls import url
from django.conf import settings

from .views import handler404, handler500, sitemap


urlpatterns = [
    url(r'^sitemap.xml$', sitemap, name='sitemap'),
    url(r'^search/', TemplateView.as_view(template_name='service/search.html'), name='search'),
]

if settings.DEBUG:
    urlpatterns = [
        url(r'^404/$', handler404, name='handler404'),
        url(r'^500/$', handler500, name='handler500'),
    ] + urlpatterns

ei60doors/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from pages import views as pages_views
from filebrowser.sites import site
from ei60doors.custom_catalog.xml import yml_export, xml_export, yml_direct


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('attachment.urls')),
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^products.yml$', yml_export),
    url(r'^direct-products.yml$', yml_direct),
    url(r'^google-products.xml$', xml_export),
    url(r'^custom_feedback/', include('ei60doors.custom_feedback.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^custom_catalog/', include('ei60doors.custom_catalog.urls')),
    url(r'^custom_pages/', include('ei60doors.custom_pages.urls')),
    url(r'^', include('ei60doors.service.urls')),
    url(r'^(?P<path>.*)/$', pages_views.details, name='pages-details-by-path'),
    url(r'^$', pages_views.details, name='pages-root', kwargs={'path': u''})
]

if settings.DEBUG:
    urlpatterns = [
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler404 = 'ei60doors.service.views.handler404'
handler500 = 'ei60doors.service.views.handler500'

try:
    from ei60doors.service.models import SiteSettings
    site_settings = SiteSettings.objects.all().first()
    if site_settings:
        admin.site.site_header = site_settings.name
except:
    pass

ei60doors/custom_pages/models.py
from django.db import models
from attachment.settings import ATTACHMENT_UPLOAD_DIR
from ei60doors.custom_catalog.models import Section, Category
from pages.models import Page
from django.core.exceptions import ValidationError


class Advantage(models.Model):

    class Meta:
        verbose_name = u'Преимущество'
        verbose_name_plural = u'Преимущества'
        ordering = ['order_key', ]

    order_key = models.PositiveIntegerField(
        verbose_name=u'',
        default=0,
        blank=False, null=False
    )
    title = models.TextField(
        verbose_name=u'Текст'
    )

    icon = models.FileField(
        verbose_name=u'Иконка',
        null=True,
        blank=True,
        upload_to=ATTACHMENT_UPLOAD_DIR
    )

    def __str__(self):
        return self.title


class CatalogItem(models.Model):
    class Meta:
        verbose_name = u'Блок "каталог"'
        verbose_name_plural = verbose_name
        ordering = ['order_key']

    order_key = models.PositiveIntegerField(verbose_name=u'', default=0, blank=False, null=False)
    section = models.ForeignKey(
        Section,
        verbose_name=u'раздел',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    category = models.ForeignKey(
        Category,
        verbose_name=u'категория',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    def clean(self):
        """Ensure that only one of `section` and `category` can be set."""
        if self.section and self.category or not self.section and not self.category:
            raise ValidationError("Нужно выбрать либо категорию, либо раздел")
        return super(CatalogItem, self).clean()

    def __str__(self):
        return 'Выберите раздел или категорию'

    def get_item(self):
        if self.section:
            return self.section
        else:
            return self.category

ei60doors/custom_catalog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Section, Product, Root, Category
from django.contrib.admin.widgets import FilteredSelectMultiple


class RootAdminForm(forms.ModelForm):

    class Meta:
        model = Root
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'large-input'}),
            'long_title': forms.TextInput(attrs={'class': 'large-input'}),
        }


class ProductAdminForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'large-input'}),
            'slug': forms.TextInput(attrs={'class': 'large-input'}),
            'price': forms.TextInput(attrs={'class': 'large-input'}),
            'finish': FilteredSelectMultiple(verbose_name='Варианты отделки', is_stacked=False),
        }


class SectionAdminForm(forms.ModelForm):

    class Meta:
        model = Section
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'large-input'}),
            'slug': forms.TextInput(attrs={'class': 'large-input'}),
            'finish': FilteredSelectMultiple(verbose_name='Варианты отделки', is_stacked=False),
        }


class CategoryAdminForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'large-input'}),
            'slug': forms.TextInput(attrs={'class': 'large-input'}),
            'products': FilteredSelectMultiple(verbose_name='Товары', is_stacked=False),
        }

ei60doors/custom_feedback/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail.message import EmailMessage
from feedback.forms import BaseFeedbackForm
from django.core.exceptions import ValidationError


def validate_is_human(value):
    if value != 'on':
        raise forms.ValidationError(':(')
    return value


def validate_file_size(value):
    filesize = value.size

    if filesize > 5242880:
        raise ValidationError(u"Максимальный размер файла 5 мб")
    else:
        return value


class BaseForm(BaseFeedbackForm):

    ERROR_MESSAGES = {
        'required': u'Заполните поле',
        'invalid': u'Неправильное значение'
    }

    confirm = forms.BooleanField(
        label=u'Согласие на обработку',
        required=True,
        initial=True
    )

    flag = forms.CharField(
        label=u'Флаг',
        required=False,
        widget=forms.widgets.HiddenInput,
        initial='none',
        validators=[validate_is_human],
    )

    def after_mail(self, **kwargs):

        """ Дополнительная логика после отправки письма
            данные данные формы доступны через self """
        pass

    def __init__(self, *args, **kwargs):

        """ Указание начальных данных формы, например переопределит тексты ошибок """

        super(BaseForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].error_messages = self.ERROR_MESSAGES


class MeteringCall(BaseForm):

    """
        Запросить расчет
    """

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )

    file = forms.FileField(
        label=u'Прикрепить файл',
        validators=[validate_file_size],
        required=False,
        help_text=u'Допустимый для загрузки формат: JPG, PNG, PDF, до 5 Мб',
        widget=forms.FileInput(
            attrs={
                'data-accept-imgfile':''
            }
        )
    )

    message = forms.CharField(
        label=u'Ваше сообщение:',
        max_length=1000,
        required=False,
        widget=forms.Textarea(
            attrs={
            }
        ),
    )

    def mail(self, request):

        message = self.render_message(request)
        headers = {}
        if 'email' in self.cleaned_data:
            headers = {'Reply-to': self.cleaned_data.get('email')}

        msg = EmailMessage(self.subject, message, self.sender, self.recipients, headers=headers)
        if request.FILES:
            uploaded_file = request.FILES['file'] # file is the name value which you have provided in form for file field
            msg.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
        msg.send()
        self.after_mail(message=message, headers=headers)


class FeedbackCall(BaseForm):

    """
        Обратный звонок
    """

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )


class Order(BaseForm):

    """
        Оформить предзаказ
    """

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )
    message = forms.CharField(
        label=u'Ваше сообщение:',
        max_length=1000,
        required=False,
        widget=forms.TextInput(
            attrs={
            }
        ),
    )


class CallRackman(BaseForm):

    """
        Вызвать замерщика
    """

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )
    date_call = forms.DateTimeField(
        label=u'Желаемая дата замера:*',
    )
    time_call = forms.TimeField(
        label=u'Желаемое время замера:',
        required=False,
        widget=forms.TimeInput(
            attrs={
                'placeholder': 'Желаемое время замера'
            }
        ),
    )


class WantSimilar(BaseForm):

    """
        Интересует похожее изделие
    """

    image_url = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )
    message = forms.CharField(
        label=u'Ваше сообщение:',
        max_length=1000,
        required=False,
        widget=forms.TextInput(
            attrs={
            }
        ),
    )


class Consult(BaseForm):

    """
        Получить консультацию
    """

    name = forms.CharField(
        label=u'Ваше имя:*',
        widget=forms.TextInput(
            attrs={

            }
        ),
    )
    phone = forms.CharField(
        label=u'Ваш телефон:*',
        widget=forms.TextInput(
            attrs={
                'placeholder':'+7 (___) ___-__-__',
            }
        ),
    )

ei60doors/custom_catalog/views.py
from django.views.generic import TemplateView
from ei60doors.custom_catalog.models import Section, Category, Root, Product
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.template import loader
from django.shortcuts import render


class FilterProductView(TemplateView):
    """ Фильтр каталога """

    template_name = 'catalog/parts/product_list.html'

    def get(self, request):
        ct_id = request.GET.get('ct')
        obj_id = request.GET.get('obj')
        dir = request.GET.get('dir')
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')
        if ct_id and obj_id:
            object = ContentType.objects.filter(id=ct_id).first().get_all_objects_for_this_type().filter(id=obj_id).first()
        else:
            object = Root.objects.first()

        products = object.get_products()
        if dir == 'asc':
            products = products.order_by('price')
        elif dir == 'desc':
            products = products.order_by('-price')

        if min_price:
            products = products.filter(price__gte=min_price)
        if max_price:
            products = products.filter(price__lte=max_price)

        context ={
            'product_list': products,
        }
        if request.is_ajax():
            html = loader.render_to_string(self.template_name, context, request)
            response_data = {
                'html': html,
                'products_count': products.count(),
            }
            return JsonResponse(response_data)
        return self.render_to_response(context)


def popular_items_pagination(request):

    novelties = Product.objects.filter(show=True,).order_by('-id')

    html = loader.render_to_string(
        'catalog/parts/novelties_list.html',
        {'novelties': novelties},
        request
    )
    response_data = {
        'html': html
    }

    return JsonResponse(response_data)

ei60doors/custom_feedback/views.py
from django.shortcuts import render
from feedback.utils import get_feedback_form
from feedback.settings import PREFIX_KEY_FIELDS


def ajax_reset_form(request):
    form_key = request.GET.get('form_key')
    form = get_feedback_form(form_key)
    if PREFIX_KEY_FIELDS:
        form.prefix = form_key
    templates = ['feedback/%s/feedback.html' % form_key, 'feedback/feedback.html']
    return render(request, templates, {'form': form})

ei60doors/custom_pages/views.py
from pages.models import Page
from django.http import JsonResponse
from django.template import loader
from django.http import HttpResponseNotFound


def pages_list_pagination(request, obj_id):

    page = Page.objects.filter(id=obj_id).first()
    if page:
        children = page.get_children_for_frontend()

        html = loader.render_to_string(
            'pages/parts/card_list.html',
            {'children': children, 'current_page': page},
            request
        )
        response_data = {
            'html': html
        }

        return JsonResponse(response_data)
    return HttpResponseNotFound

ei60doors/service/views.py
# -*- coding: utf-8 -*-
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.shortcuts import render
from pages.models import Page
from .models import ErrorPage
from ei60doors.custom_catalog.models import Root, Section, Category, Product


def handler404(request, exception=None):
    obj, _ = ErrorPage.objects.get_or_create(type='404')
    obj.generate_static_page(request)
    return render(request, 'service/404.html', {'object': obj}, status=404)


def handler500(request):
    obj, _ = ErrorPage.objects.get_or_create(type='500')
    obj.generate_static_page(request)
    return render(request, 'service/500.html', {'object': obj}, status=500)


def sitemap(request):
    sitemaps = {
        'pages': GenericSitemap({
            'queryset': Page.objects.filter(status=Page.PUBLISHED),
            'date_field': 'last_modification_date',
        }),
        'root': GenericSitemap({
            'queryset': Root.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'section': GenericSitemap({
            'queryset': Section.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'category': GenericSitemap({
            'queryset': Category.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
        'product': GenericSitemap({
            'queryset': Product.objects.filter(show=True),
            'date_field': 'last_modified',
        }),
    }
    return sitemap_view(request, sitemaps, template_name='service/sitemap.xml')

ei60doors/templates/pages/base.html
{% extends 'base.html' %}
{% load pages_tags custom_pages_tags seo_tags %}

{% block seo %}
    {% seo current_page title_default=current_page.title %}
{% endblock %}

{% block content_title %}
    {% placeholder long_title label 'Длинный заголовок' as long_title %}
    {{ long_title|default:current_page.title }}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% pages_breadcrumb current_page %}
{% endblock %}

{% block footer %}
    {% placeholder hide_map label 'Скрыть карту в подвале сайта' with Checkbox as hide_map %}
    {{ block.super }}
{% endblock %}

ei60doors/templates/pages/breadcrumb.html
{% load pages_tags %}
{% for page in pages_navigation %}
    <li class="breadcrumbs__item">
        <a class="breadcrumbs__content" cursor-class="link-hover" href="{{ page.get_absolute_url }}">
            {{ page.title }}
        </a>
        <span class="breadcrumbs__content">
            /
        </span>
    </li>
{% endfor %}

ei60doors/templates/pages/frontpage.html
{% extends 'pages/base.html' %}
{% load custom_pages_tags attachment_tags pages_tags base_tags %}

{% block header-options %}header--dark{% endblock %}
{% block header_bg %}{% endblock %}
{% block breadcrumbs_section %}{% endblock %}
{% block title_section %}{% endblock %}
{% block page-options %}page--nopadding{% endblock %}

{% block content %}
    {% if current_page.get_children %}
        <section class="intro">
            <div class="intro__slider intro--slider swiper-container">
                <div class="swiper-wrapper">
                    {% for slide in current_page.get_children %}
                        <div class="intro__slider-item swiper-slide {% if forloop.first %}intro__slider-item--first{% endif %}">
                            {% get_images for slide as images %}
                            {% if images %}
                                <div class="intro__slider-bg" data-swiper-parallax="50%" style="background-image: url('{{ images.0.image.url }}');"></div>
                            {% endif %}
                            <div class="container">
                                <div class="intro__content">
                                    <div class="intro__content-title">
                                        {{ slide.title }}
                                    </div>
                                    {% get_content slide 'subtitle' as subtitle %}
                                    {% if subtitle %}
                                        <div class="intro__content-subtitle">
                                            {{ subtitle }}
                                        </div>
                                    {% endif %}
                                    {% get_content slide 'text' as text %}
                                    {% if text %}
                                        <div class="intro__content-info">
                                            {{ text }}
                                        </div>
                                    {% endif %}

                                    {% get_content slide 'link' as link %}
                                    {% if link %}
                                        <a class="btn btn--red intro__content-btn" cursor-class="link-hover" href="{{ link }}">
                                            Подробнее
                                        </a>
                                     {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="intro__pagination"></div>
        </section>
    {% endif %}

    {% get_items_by_model_name 'advantage' ordering='order_key' num=4 as advantages %}
    {% if advantages %}
        <section class="section-default-md section-default--bottom content-anim content-anim--opacity">
            <div class="container">
                <div class="advantages">
                    {% for advantage in advantages %}
                        <div class="advantages__item">
                            {% if advantage.icon %}
                                <div class="advantages__item-icon">
                                    <img src="{{ advantage.icon.url }}" alt="{{ advantage.title }}">
                                </div>
                            {% endif %}
                            <span class="advantages__item-title">
                                {{ advantage.title }}
                            </span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    {% if current_page.catalogitem_set.all %}
        <section class="section-default-md section-default--bottom content-anim content-anim--bottom">
            <div class="container">
                <div class="division">
                    <div class="division__grid scroll-custom-x-hidden--xs">
                        {% for item in current_page.catalogitem_set.all %}
                            <div class="division__item">
                                <a class="division-card" cursor-class="link-hover" href="{{ item.get_item.get_absolute_url }}">
                                    <div class="division-card__content">
                                        <div class="division-card__title">
                                            {{ item.get_item.title }}
                                        </div>
                                    </div>
                                    {% get_images for item.get_item as images %}
                                    {% if images %}
                                        <div class="division-card-img">
                                            <img src="{{ images.0.divisioncard.url }}" alt="{{ images.0.title|default:item.get_item.title }}" title="{{ images.0.title|default:item.get_item.title }}">
                                        </div>
                                    {% endif %}
                                </a>
                            </div>
                        {% endfor %}
                        <div class="division__item">
                            <a class="division-card" href="{% url 'catalog-root' %}">
                                <div class="division-card__content">
                                    <div class="division-card__title">
                                        СМОТРЕТЬ ВЕСЬ КАТАЛОГ
                                    </div>
                                    <div class="link-line link-line--white division-card__link">
                                        <span class="link-line__text">
                                            Смотреть все
                                        </span>
                                        <div class="link-line__icon">
                                            <span>
                                                <svg width="50" height="9" viewBox="0 0 50 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M45.53 0.21934L49.28 3.96934C49.5725 4.26216 49.5725 4.73652 49.28 5.02934L45.53 8.77934C45.343 8.97999 45.0614 9.06259 44.7957 8.99473C44.53 8.92686 44.3225 8.71936 44.2546 8.45363C44.1867 8.1879 44.2693 7.90631 44.47 7.71934L46.94 5.24934H0.75C0.335786 5.24934 0 4.91355 0 4.49934C0 4.08513 0.335786 3.74934 0.75 3.74934H46.94L44.47 1.27934C44.1775 0.986522 44.1775 0.512158 44.47 0.21934C44.7628 -0.0731133 45.2372 -0.0731133 45.53 0.21934Z" fill="black"/>
                                                </svg>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}

    {% get_items_by_model_name 'product' ordering='-id' show=True as novelties %}
    {% if novelties.exists %}
        <section class="section-default section-default--bottom content-anim content-anim--opacity">
            <div class="container">
                <div class="title-content">
                    <div class="title">
                        Новинки каталога
                    </div>
                </div>

                <div class="catalog__grid ajax-update">
                    {% include 'catalog/parts/novelties_list.html' %}
                </div>
            </div>
        </section>
    {% endif %}

    {% placeholder work_samples with GallerySelect label 'Галерея "Примеры готовых изделий"' as work_samples %}
    {% if work_samples %}
        {% get_page work_samples as work_samples_gallery %}
        {% if work_samples_gallery %}
            <section class="section-default section-default-margin section-default-margin--bottom section-grey content-anim content-anim--opacity">
                <div class="container">
                    {% include 'parts/work_samples_gallery.html' with gallery=work_samples_gallery %}
                </div>
            </section>
        {% endif %}
    {% endif %}

    {% placeholder factory_content label 'блок "Завод конструкций"' with TinyMCE as factory_content %}
    {% placeholder factory_content_link label 'ссылка "Завод конструкций"' as factory_content_link %}
    {% get_images for current_page as images %}
    {% get_image_groups for images as image_groups %}
    {% if factory_content %}
        <section class="section-default section-dark section-relative section-about">
            <div class="container">
                <div class="about">
                    <div class="about__content">
                        <div class="placeholder placeholder--white">
                            {{ factory_content|safe }}
                        </div>
                        {% if factory_content_link %}
                            <a class="link-line link-line--white about__link" cursor-class="link-hover" href="{{ factory_content_link }}">
                                <span class="link-line__text">
                                    Узнать больше
                                </span>
                                <div class="link-line__icon">
                                    <span>
                                        <svg width="50" height="9" viewBox="0 0 50 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M45.53 0.21934L49.28 3.96934C49.5725 4.26216 49.5725 4.73652 49.28 5.02934L45.53 8.77934C45.343 8.97999 45.0614 9.06259 44.7957 8.99473C44.53 8.92686 44.3225 8.71936 44.2546 8.45363C44.1867 8.1879 44.2693 7.90631 44.47 7.71934L46.94 5.24934H0.75C0.335786 5.24934 0 4.91355 0 4.49934C0 4.08513 0.335786 3.74934 0.75 3.74934H46.94L44.47 1.27934C44.1775 0.986522 44.1775 0.512158 44.47 0.21934C44.7628 -0.0731133 45.2372 -0.0731133 45.53 0.21934Z" fill="black"/>
                                        </svg>
                                    </span>
                                </div>
                            </a>
                        {% endif %}
                    </div>

                    {% with factory_bg=image_groups|key:'завод' %}
                        {% if factory_bg %}
                            <div class="about__preview">
                                <div class="about__preview-big">
                                    <div class="img-anim">
                                        <img src="{{ factory_bg.0.image.url }}" alt="Завод противопожарных конструкций">
                                    </div>
                                </div>
                                <div class="about__preview-min">
                                    <div class="img-anim">
                                        <img src="{{ factory_bg.1.image.url }}" alt="Завод противопожарных конструкций">
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </section>
    {% endif %}

    {% placeholder clients with GallerySelect label 'Клиенты и партнеры' as clients %}
    {% if clients %}
        {% get_page clients as clients_gallery %}
        {% if clients_gallery %}
            <section class="section-default content-anim content-anim--opacity">
                <div class="container">
                    {% include 'parts/clients_gallery.html' %}
                </div>
            </section>
        {% endif %}
    {% endif %}
{% endblock %}

ei60doors/templates/pages/list.html
{% extends 'pages/base.html' %}
{% load pages_tags custom_pages_tags pagination_tags attachment_tags base_tags %}

{% block content %}
    {% placeholder top_content with TinyMCE label 'Контент сверху' as top_content %}
    {% if top_content %}
        <section class="section-default section-default--top content-anim content-anim--opacity">
            <div class="container">
                <div class="placeholder mfp-gallery">
                    {{ top_content|safe }}
                </div>
            </div>
        </section>
    {% endif %}

    {% with children=current_page.get_children_for_frontend %}
        {% if children %}
            <section class="section-default section-default--top content-anim content-anim--opacity">
                <div class="container">
                    <div class="grid">
                        {% include 'pages/parts/card_list.html' %}
                    </div>
                </div>
            </section>
        {% endif %}
    {% endwith %}
{% endblock %}

ei60doors/templates/pages/slide.html
{% load pages_tags %}

{# Используется на главной #}
{% placeholder subtitle with Textarea as subtitle %}
{% placeholder text with Textarea as text %}
{% placeholder link with Textarea as link %}